### ISSUE TITLE
Can you share the full BCDR dataset?

### ISSUE THREAD

**Issue by WangRongsheng** [iamtariqul/Segmentation-for-Breast-Cancer-by-BCDR-DM-Dataset#1]
Can you share the full BCDR dataset?

**Comment by iamtariqul** [comment]
[Download](https://bcdr.eu) dataset by create a account.

**Comment by WangRongsheng** [comment]
I sent the application email but no one ever responded to me. Who can I contact please?

**Comment by iamtariqul** [comment]
I will upload full dataset next weak, wait!

**Comment by iamtariqul** [comment]
[Download ](https://docs.google.com/spreadsheets/d/1vJpOk3DaFlOoRoCtj8AjBSdFyPMJnCMifvjDQEs2Rc8/edit?usp=sharing) Dataset

**Comment by WangRongsheng** [comment]
Thank you , but that doesn't seem to include images? @iamtariqul

**Comment by iamtariqul** [comment]
All images you can find on this [website](https://bcdr.eu/patient/list)!

**Comment by WangRongsheng** [comment]
Requesting a download is very difficult! I've been waiting for a month and still haven't gotten an email response.

**Comment by WangRongsheng** [comment]
@iamtariqul hi？Requesting a download is very difficult! I've been waiting for a month and still haven't gotten an email response.
